[package]
name = "cargo-actix-openapi"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { version = "*", features = ["derive"] }
serde_yaml = "*"
openapiv3 = "*"
anyhow = "*"
convert_case = "*"

[dev-dependencies]
pretty_assertions = "*"
rstest = "*"
