//! API auto-generated by apigen

use std::fmt::Display;

use std::{collections::HashMap, fmt::Debug};

use serde::{Deserialize, Serialize};

use actix_web::{
    get, http::StatusCode, middleware::NormalizePath, web, App, HttpRequest, HttpResponse,
    HttpServer, ResponseError,
};

use async_trait::async_trait;

// Enums
// -------------------------------

/// String enum example
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
pub enum GreetUserResponseStrEnum {
    #[serde(rename = "First Variant")]
    FirstVariant,
    #[serde(rename = "Second variant $")]
    SecondVariant,
    #[serde(rename = "!123")]
    V123,
    #[serde(rename = "Hello, \"World\"")]
    HelloWorld,
    #[serde(rename = "Hello, \\\"World2\\\"!")]
    HelloWorld2,
}
