//! API auto-generated by apigen

use std::fmt::Display;

use std::{collections::HashMap, fmt::Debug};

use serde::{Deserialize, Serialize};

use actix_web::{
    get, http::StatusCode, middleware::NormalizePath, web, App, HttpRequest, HttpResponse,
    HttpServer, ResponseError,
};

use async_trait::async_trait;

// Defaults
// -------------------------------

fn default_int_1() -> i64 {
    1
}

fn default_float_0_1() -> f64 {
    0.1
}


// Enums
// -------------------------------


// Struct
// -------------------------------

#[derive(Serialize, Deserialize, Clone, PartialEq)]
pub struct GreetUserPath {
    pub user: String,
}

#[derive(Serialize, Deserialize, Clone, PartialEq)]
pub struct GreetUserBodyObj {
    #[serde(default="default_int_1")]
    pub foo: i64,
    #[serde(default="default_float_0_1")]
    pub bar: f64,
}

#[derive(Serialize, Deserialize, Clone, PartialEq)]
pub struct GreetUserBody {
    pub str: String,
    pub obj: GreetUserBodyObj,
}
