#![allow(unused_imports, dead_code)]

//! API auto-generated by apigen

use std::{
    collections::HashMap,
    fmt::{Debug, Display},
};

use serde::{Deserialize, Serialize};

use actix_web::{
    http::StatusCode,
    middleware::{NormalizePath, TrailingSlash},
    web, App, HttpRequest, HttpResponse, HttpServer, ResponseError,
};

use actix_web_prom::{PrometheusMetrics, PrometheusMetricsBuilder};

use async_trait::async_trait;

// Defaults
// -------------------------------

// Enums
// -------------------------------

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
pub enum HealthResponse {
    Ok,
}

// Struct
// -------------------------------

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
pub struct HelloUserPath {
    /// The name of the user to greet.
    pub user: String,
}

// Error with details
// -------------------------------

/// Create detailed errors with ease
#[macro_export]
macro_rules! detailed {
    ($err:expr,$msg:expr) => {
        $crate::server::api::Detailed {
            error: $err,
            details: $msg.to_string(),
        }
    };
}

/// Bails with detailed api error
#[macro_export]
macro_rules! apibail {
    ($err:expr,$msg:expr) => {
        return Err($crate::server::api::Detailed {
            error: $err,
            details: $msg.to_string(),
        })
    };
}

pub trait StatusCoded {
    fn status_code(&self) -> StatusCode;
}

#[derive(Debug)]
pub struct Detailed<E> {
    pub error: E,
    pub details: String,
}

impl<E: Display> Display for Detailed<E> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}. Reason: {}", self.error, self.details)
    }
}

impl<E: Display + Debug> std::error::Error for Detailed<E> {}

impl<E: Display + Debug> ResponseError for Detailed<E>
where
    E: StatusCoded,
{
    fn status_code(&self) -> StatusCode {
        self.error.status_code()
    }
}

/// Converts some result to Result with detailed api error
pub trait ApiErr<T, E> {
    /// Wrap the error value with additional context.
    fn apierr<C>(self, err: C) -> Result<T, Detailed<C>>
    where
        C: Display + Send + Sync + 'static;
}

impl<T, E> ApiErr<T, E> for Result<T, E>
where
    E: Debug + Send + Sync + 'static,
{
    fn apierr<C>(self, err: C) -> Result<T, Detailed<C>>
    where
        C: Display + Send + Sync + 'static,
    {
        // Not using map_err to save 2 useless frames off the captured backtrace
        // in ext_context.
        match self {
            Ok(ok) => Ok(ok),
            Err(original_error) => Err(Detailed {
                error: err,
                details: format!("{:?}", original_error),
            }),
        }
    }
}

// Error
// -------------------------------

/// Status BAD_REQUEST:
/// Invalid characters in "user" were provided.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
pub enum HelloUserError {
    InvalidCharacters,
}

impl Display for HelloUserError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let message = match self {
            Self::InvalidCharacters => "Invalid characters",
        };
        f.write_str(message)
    }
}

impl StatusCoded for HelloUserError {
    fn status_code(&self) -> StatusCode {
        match self {
            Self::InvalidCharacters => StatusCode::BAD_REQUEST,
        }
    }
}

// Api service
// -------------------------------

#[async_trait(?Send)]
pub trait ApiService<S>
where
    S: Send + Sync + 'static,
{
    /// Service Health check
    async fn health(
        data: web::Data<S>,
    ) -> web::Json<HealthResponse>;
    /// Returns a greeting to the user!
    async fn hello_user(
        data: web::Data<S>,
        path: web::Path<HelloUserPath>,
    ) -> Result<web::Json<String>, Detailed<HelloUserError>>;
}

// Run service function (+ helper functions)
// -----------------------------------------
static DOCS_OPENAPI: &str = include_str!("openapi.yaml");
static DOCS_HTML: &str = include_str!("docs.html");
async fn openapi() -> String {
    DOCS_OPENAPI.to_string()
}
async fn docs() -> HttpResponse {
    HttpResponse::build(StatusCode::OK)
        .content_type("text/html; charset=utf-8")
        .body(DOCS_HTML)
}
async fn to_v1_docs() -> HttpResponse {
    HttpResponse::build(StatusCode::TEMPORARY_REDIRECT)
        .append_header(("Location", "v1/docs"))
        .body("")
}
async fn to_docs() -> HttpResponse {
    HttpResponse::build(StatusCode::TEMPORARY_REDIRECT)
        .append_header(("Location", "docs"))
        .body("")
}

// Tells that service is alive
async fn health() -> HttpResponse {
    HttpResponse::Ok().finish()
}


/// Just make scope - can be used for manual server creation
/// And to combine with other scopes
pub fn make_scope<T, S>(prometheus: PrometheusMetrics) -> actix_web::Scope
where
    T: ApiService<S> + 'static,
    S: Send + Sync + 'static,
{
    use web::{delete, get, post};

    let api = web::scope("")
        .route("/health", get().to(T::health))
        .route("/hello/{user}", get().to(T::hello_user))
        .route("/v1/health", get().to(T::health))
        .route("/v1/hello/{user}", get().to(T::hello_user))
        .wrap(prometheus);

    web::scope("")
        // Aux services
        .route("/health", get().to(health))
        // Static paths
        .route("/", get().to(to_docs))
        .route("/docs", get().to(docs))
        .route("/openapi.yaml", get().to(openapi))
        .route("/v1", get().to(to_v1_docs))
        .route("/v1/", get().to(to_docs))
        .route("/v1/docs", get().to(docs))
        .route("/v1/openapi.yaml", get().to(openapi))
        // Server routes
        .service(api)
}
